# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3d6fed01a2afd5a84b0ff499452fac3d0c1103d38220b327e184eb6f6f354827e3862894df7e89752c32fdc2fc44b9956a2dc7a45c05380ff1050f1952dda7e

test:
  secret_key_base: 99c6b737ddd6dac50d46712fbe589981af25b8c88791cb8eddcfb4e844e992ffb2f323dbd97c17a6137aa8ae48f8b2faa99bd7206b2d91e3d979d55e2546d451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
